name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Setup Graphviz
      uses: kamiazya/setup-graphviz@v1
    - name: Dump Environment
      run: env
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test
    - name: Pack
      run: dotnet pack
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Artifacts
        path: _artifacts
