name: Release
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifiact
      uses: actions/download-artifact@v1.0.0
      with:
        name: Artifacts- ${{ github.sha }}
